data:
  trial_names: # the names of the trials. It has to correspond with the trial_types parameter
    - "thigh_right_angled_incipient"

  trial_types: ["sim"] # set this parameter to "sim" for using simulation data and "real" for real data
  force_type_to_keep: ["all"] # for each corresponding trials listed, choose the force type to keep. Either "slow", "fast", "intermittent" or "all"
  relative_feature_data_path: "./..digit_data/feature_data"